'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class InterNICEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=InterNICEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function sp_CancelLeave(leaveId As Nullable(Of Integer)) As Integer
        Dim leaveIdParameter As ObjectParameter = If(leaveId.HasValue, New ObjectParameter("leaveId", leaveId), New ObjectParameter("leaveId", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_CancelLeave", leaveIdParameter)
    End Function

    Public Overridable Function sp_DeleteUser(userId As Nullable(Of Integer)) As Integer
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("userId", userId), New ObjectParameter("userId", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_DeleteUser", userIdParameter)
    End Function

    Public Overridable Function sp_GetBirthdayList() As ObjectResult(Of sp_GetBirthdayList_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_GetBirthdayList_Result)("sp_GetBirthdayList")
    End Function

    Public Overridable Function sp_getDateInOutDetails(fpdate As Nullable(Of Date)) As ObjectResult(Of sp_getDateInOutDetails_Result)
        Dim fpdateParameter As ObjectParameter = If(fpdate.HasValue, New ObjectParameter("fpdate", fpdate), New ObjectParameter("fpdate", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_getDateInOutDetails_Result)("sp_getDateInOutDetails", fpdateParameter)
    End Function

    Public Overridable Function sp_getDesignation(desigId As Nullable(Of Integer)) As ObjectResult(Of sp_getDesignation_Result)
        Dim desigIdParameter As ObjectParameter = If(desigId.HasValue, New ObjectParameter("desigId", desigId), New ObjectParameter("desigId", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_getDesignation_Result)("sp_getDesignation", desigIdParameter)
    End Function

    Public Overridable Function sp_getHolidays(id As Nullable(Of Integer)) As ObjectResult(Of sp_getHolidays_Result)
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_getHolidays_Result)("sp_getHolidays", idParameter)
    End Function

    Public Overridable Function sp_getLeaves(userId As Nullable(Of Integer), leaveId As Nullable(Of Integer)) As ObjectResult(Of sp_getLeaves_Result)
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("userId", userId), New ObjectParameter("userId", GetType(Integer)))

        Dim leaveIdParameter As ObjectParameter = If(leaveId.HasValue, New ObjectParameter("leaveId", leaveId), New ObjectParameter("leaveId", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_getLeaves_Result)("sp_getLeaves", userIdParameter, leaveIdParameter)
    End Function

    Public Overridable Function sp_GetMonthlyReport(month As Nullable(Of Integer), year As Nullable(Of Integer), userId As Nullable(Of Integer)) As ObjectResult(Of sp_GetMonthlyReport_Result)
        Dim monthParameter As ObjectParameter = If(month.HasValue, New ObjectParameter("month", month), New ObjectParameter("month", GetType(Integer)))

        Dim yearParameter As ObjectParameter = If(year.HasValue, New ObjectParameter("year", year), New ObjectParameter("year", GetType(Integer)))

        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("userId", userId), New ObjectParameter("userId", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_GetMonthlyReport_Result)("sp_GetMonthlyReport", monthParameter, yearParameter, userIdParameter)
    End Function

    Public Overridable Function sp_GetNotification() As ObjectResult(Of sp_GetNotification_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_GetNotification_Result)("sp_GetNotification")
    End Function

    Public Overridable Function sp_GetUserForDisplay(userId As Nullable(Of Integer)) As ObjectResult(Of sp_GetUserForDisplay_Result)
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("userId", userId), New ObjectParameter("userId", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_GetUserForDisplay_Result)("sp_GetUserForDisplay", userIdParameter)
    End Function

    Public Overridable Function sp_GetUserFP() As ObjectResult(Of sp_GetUserFP_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_GetUserFP_Result)("sp_GetUserFP")
    End Function

    Public Overridable Function sp_getUserInOutDetails(userId As Nullable(Of Integer), month As Nullable(Of Integer), year As Nullable(Of Integer)) As ObjectResult(Of sp_getUserInOutDetails_Result)
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("userId", userId), New ObjectParameter("userId", GetType(Integer)))

        Dim monthParameter As ObjectParameter = If(month.HasValue, New ObjectParameter("month", month), New ObjectParameter("month", GetType(Integer)))

        Dim yearParameter As ObjectParameter = If(year.HasValue, New ObjectParameter("year", year), New ObjectParameter("year", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_getUserInOutDetails_Result)("sp_getUserInOutDetails", userIdParameter, monthParameter, yearParameter)
    End Function

    Public Overridable Function sp_MarkLeave(userId As Nullable(Of Integer), ctdate As Nullable(Of Date)) As Integer
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("userId", userId), New ObjectParameter("userId", GetType(Integer)))

        Dim ctdateParameter As ObjectParameter = If(ctdate.HasValue, New ObjectParameter("ctdate", ctdate), New ObjectParameter("ctdate", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_MarkLeave", userIdParameter, ctdateParameter)
    End Function

    Public Overridable Function sp_RemoveDesignation(desigID As Nullable(Of Integer)) As Integer
        Dim desigIDParameter As ObjectParameter = If(desigID.HasValue, New ObjectParameter("desigID", desigID), New ObjectParameter("desigID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_RemoveDesignation", desigIDParameter)
    End Function

    Public Overridable Function sp_RemoveHoliday(recId As Nullable(Of Integer)) As Integer
        Dim recIdParameter As ObjectParameter = If(recId.HasValue, New ObjectParameter("recId", recId), New ObjectParameter("recId", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_RemoveHoliday", recIdParameter)
    End Function

    Public Overridable Function sp_SaveDesignation(desigId As Nullable(Of Integer), desigName As String) As Integer
        Dim desigIdParameter As ObjectParameter = If(desigId.HasValue, New ObjectParameter("desigId", desigId), New ObjectParameter("desigId", GetType(Integer)))

        Dim desigNameParameter As ObjectParameter = If(desigName IsNot Nothing, New ObjectParameter("desigName", desigName), New ObjectParameter("desigName", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_SaveDesignation", desigIdParameter, desigNameParameter)
    End Function

    Public Overridable Function sp_SaveHolidays(id As Nullable(Of Integer), title As String, fromdate As Nullable(Of Date), todate As Nullable(Of Date)) As Integer
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Integer)))

        Dim titleParameter As ObjectParameter = If(title IsNot Nothing, New ObjectParameter("title", title), New ObjectParameter("title", GetType(String)))

        Dim fromdateParameter As ObjectParameter = If(fromdate.HasValue, New ObjectParameter("fromdate", fromdate), New ObjectParameter("fromdate", GetType(Date)))

        Dim todateParameter As ObjectParameter = If(todate.HasValue, New ObjectParameter("todate", todate), New ObjectParameter("todate", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_SaveHolidays", idParameter, titleParameter, fromdateParameter, todateParameter)
    End Function

    Public Overridable Function sp_SaveUserDetails(userID As Nullable(Of Integer), fullName As String, designation As String, joiningdate As Nullable(Of Date), birthdate As Nullable(Of Date), isAdmin As Nullable(Of Integer), mobileNO As String) As Integer
        Dim userIDParameter As ObjectParameter = If(userID.HasValue, New ObjectParameter("userID", userID), New ObjectParameter("userID", GetType(Integer)))

        Dim fullNameParameter As ObjectParameter = If(fullName IsNot Nothing, New ObjectParameter("fullName", fullName), New ObjectParameter("fullName", GetType(String)))

        Dim designationParameter As ObjectParameter = If(designation IsNot Nothing, New ObjectParameter("designation", designation), New ObjectParameter("designation", GetType(String)))

        Dim joiningdateParameter As ObjectParameter = If(joiningdate.HasValue, New ObjectParameter("joiningdate", joiningdate), New ObjectParameter("joiningdate", GetType(Date)))

        Dim birthdateParameter As ObjectParameter = If(birthdate.HasValue, New ObjectParameter("birthdate", birthdate), New ObjectParameter("birthdate", GetType(Date)))

        Dim isAdminParameter As ObjectParameter = If(isAdmin.HasValue, New ObjectParameter("isAdmin", isAdmin), New ObjectParameter("isAdmin", GetType(Integer)))

        Dim mobileNOParameter As ObjectParameter = If(mobileNO IsNot Nothing, New ObjectParameter("mobileNO", mobileNO), New ObjectParameter("mobileNO", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_SaveUserDetails", userIDParameter, fullNameParameter, designationParameter, joiningdateParameter, birthdateParameter, isAdminParameter, mobileNOParameter)
    End Function

    Public Overridable Function sp_saveUserLeave(userId As Nullable(Of Integer), fromdate As Nullable(Of Date), todate As Nullable(Of Date)) As Integer
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("userId", userId), New ObjectParameter("userId", GetType(Integer)))

        Dim fromdateParameter As ObjectParameter = If(fromdate.HasValue, New ObjectParameter("fromdate", fromdate), New ObjectParameter("fromdate", GetType(Date)))

        Dim todateParameter As ObjectParameter = If(todate.HasValue, New ObjectParameter("todate", todate), New ObjectParameter("todate", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_saveUserLeave", userIdParameter, fromdateParameter, todateParameter)
    End Function

    Public Overridable Function sp_SubmitPresence(userId As Nullable(Of Integer)) As Integer
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("userId", userId), New ObjectParameter("userId", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_SubmitPresence", userIdParameter)
    End Function

    Public Overridable Function sp_UpdateUserFP(userID As Nullable(Of Integer), fPData As Byte(), strthumb As Byte()) As Integer
        Dim userIDParameter As ObjectParameter = If(userID.HasValue, New ObjectParameter("userID", userID), New ObjectParameter("userID", GetType(Integer)))

        Dim fPDataParameter As ObjectParameter = If(fPData IsNot Nothing, New ObjectParameter("FPData", fPData), New ObjectParameter("FPData", GetType(Byte())))

        Dim strthumbParameter As ObjectParameter = If(strthumb IsNot Nothing, New ObjectParameter("strthumb", strthumb), New ObjectParameter("strthumb", GetType(Byte())))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_UpdateUserFP", userIDParameter, fPDataParameter, strthumbParameter)
    End Function

End Class
